apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongodb.name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  mongo-user: "{{ .Values.mongodb.username }}"
  mongo-password: "{{ .Values.mongodb.password }}"

