apiVersion: v1
kind: Service
metadata:
  name: usernode-js-service
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.userprofile.port }}
      targetPort: {{ .Values.userprofile.port }}
      protocol: TCP
  selector:
    app: userprofile

